[build-system]
# this version is required to support reading of version in setup.cfg
requires = ["setuptools>=46.4.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 88
show-fixes = true
target-version = "py39"

[tool.ruff.lint]
ignore = ["BLE001"]

# TODO: Fix type errors in these files
[[tool.ty.overrides]]
include = [
  "home/code_setup.py",
  "home/computational_resources.py",
]
[tool.ty.overrides.rules]
all = "ignore"
